version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5434:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    networks:
      - service
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 1s
      timeout: 3s
      retries: 30

  gateway:
    stdin_open: true
    depends_on:
      - postgres
    links:
      - postgres
    container_name: gateway-service
    ports:
      - 8080:8080
    build:
      context: gateway-service
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    restart: always
    networks:
      - default

  car:
    stdin_open: true
    depends_on:
      - postgres
      - gateway
    links:
      - postgres
      - gateway
    container_name: car-service
    ports:
      - 8070:8070
    build:
      context: car-service
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - car-service/.env
    command: npm run start:migrate:start
    restart: always
    networks:
      - default

  rental:
    stdin_open: true
    depends_on:
      - postgres
      - gateway
    links:
      - postgres
      - gateway
    container_name: rental-service
    ports:
      - 8060:8060
    build:
      context: rental-service
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - rental-service/.env
    command: npm run start:migrate:start
    restart: always
    networks:
      - default

  payment:
    stdin_open: true
    depends_on:
      - postgres
      - gateway
    links:
      - postgres
      - gateway
    container_name: payment-service
    ports:
      - 8050:8050
    build:
      context: payment-service
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - payment-service/.env
    command: npm run start:migrate:start
    restart: always
    networks:
      - default

volumes:
  postgres-data:
networks: default
